name: GitHub Actions Version Updater

on:
  schedule:
    # Every monday at 13:37 UTC
    - cron: 37 13 * * 1
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          token: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@e9362a3a6af5b942b421fd1b66fe4b7fa0ca7714
        with:
          token: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}
          commit_message: "chore: update github workflow actions"
          pull_request_title: "chore: update github workflow actions"
          pull_request_team_reviewers: cdktf
          update_version_with: "release-commit-sha"
